name: Deploy Azure Function App

on:
  push:
    branches:
      - main
      - 002-azure-barcode-generator

env:
  AZURE_FUNCTIONAPP_NAME: bcodeKaps
  AZURE_FUNCTIONAPP_PACKAGE_PATH: src
  PYTHON_VERSION: '3.11'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/requirements.txt
          pip install pytest python-barcode Pillow

      - name: Run tests
        run: pytest

      - name: Create deployment package
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          zip -r ../functionapp.zip . -x '*__pycache__*' '*.pytest_cache*'

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: functionapp.zip
          scm-do-build-during-deployment: true
          enable-oryx-build: true
          remote-build: true
